-- Helixa-One: Database Schema for Supabase

-- 1. Telemetry Table (Time-series optimized)
CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    sensor_id TEXT NOT NULL,
    type TEXT NOT NULL,
    value FLOAT8 NOT NULL,
    unit TEXT NOT NULL
);

-- 2. Enable Realtime for the telemetry table
ALTER PUBLICATION supabase_realtime ADD TABLE telemetry;

-- 3. Index for faster queries on sensor_id and created_at
CREATE INDEX IF NOT EXISTS idx_telemetry_sensor_time ON telemetry (sensor_id, created_at DESC);
